import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";

const BADGES = ["SOLO", "CREW", "CLAN", "SQUAD", "LEGION", "EMPIRE"];
interface Props {
  SPL_TOKENS: string[];
}
export const getServerSideProps: GetStaticProps<Props> = async () => {
  const SPL_TOKENS = BADGES.map(
    (badge) => process.env[`NEXT_PUBLIC_WL_MINT_${badge.toUpperCase()}`]
  ) as string[];

  return {
    props: {
      SPL_TOKENS,
    },
  };
};

const Home: NextPage<Props> = ({ SPL_TOKENS }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {SPL_TOKENS.map((token: string) => (
          <div key={token}>{token}</div>
        ))}
      </main>
    </div>
  );
};

export default Home;
