import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { GetStaticProps } from "next";
import { useConnection, useWallet } from "@solana/wallet-adapter-react";
import { rpcMethods } from "lib/spl";
import { useEffect, useState } from "react";

const BADGES = ["SOLO", "CREW", "CLAN", "SQUAD", "LEGION", "EMPIRE"];
interface Props {
  SPL_TOKENS: string[];
}
export const getServerSideProps: GetStaticProps<Props> = async () => {
  const SPL_TOKENS = BADGES.map(
    (badge) => process.env[`NEXT_PUBLIC_WL_MINT_${badge.toUpperCase()}`]
  ) as string[];

  return {
    props: {
      SPL_TOKENS,
    },
  };
};
const owner = "BoX451MZzydoVdZE4NFfmMT3J5Ztqo7YgUNbwwMfjPFu";

const Home: NextPage<Props> = ({ SPL_TOKENS }) => {
  const { connection } = useConnection();
  const [mints, setMints] = useState<{ mint: string; amount: number }[]>([]);
  async function getTokenMints() {
    const _mints = await Promise.all(
      SPL_TOKENS.map(async (mint) => {
        const amount = await new rpcMethods(connection).getTokenBalance(
          owner,
          mint
        );
        return {
          mint,
          amount,
        };
      })
    );
    setMints(_mints);
  }
  useEffect(() => {
    getTokenMints();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {mints.map(({ mint, amount }) => (
          <div key={mint}>
            {mint} {amount}
            <button>Mint more</button>
            <button>Transfer</button>
          </div>
        ))}
      </main>
    </div>
  );
};

export default Home;
