name: Deploy preview
on: [pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Output the variables
        run: |
          echo The major was $MAJOR
          echo The minor was $MINOR
          echo The patch was $PATCH
          echo The pre-release was $PRE_RELEASE
          echo The number of commits was $NUMBER_OF_COMMITS
          echo The number of commits since tag was $NUMBER_OF_COMMITS_SINCE_TAG
      - name: save version file
        uses: satackey/action-js-inline@v0.0.2
        id: getdata
        with:
          # Edit the following line to install packages required to run your script.
          script: |
            const core = require('@actions/core')

            // branch
            console.log("major, $MAJOR")
            console.log(`major: ${$MAJOR}`)
            console.log(`minor: ${$MINOR}`)
            console.log(`patch: ${$PATCH}`)
         

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          PRODUCTION: false # Don't deploy to production environment
